### ISSUE TITLE
How to do downstream analysis of PlanOut experiments? Any tools available?

### ISSUE THREAD

**Issue by LABCAO** [facebook/planout#119]
Checking both the implementation of PlanOut and the PlanOut paper, it's NOT clear how to do downstream analysis of PlanOut experiments programmatically / automatically? Any tools out there available?

Can anyone please shed some light on this? Thanks very much!

**Comment by eytan** [comment]
Hi @LABCAO,

You might want to check out this online tutorial, which walks you through how to save and parse logged data, and how to evaluate the effectiveness of your experiments using R.

Part of what's complicated about all of this is it depends on what your stack is. At Facebook (as described in the PlanOut paper (http://hci.stanford.edu/publications/2014/planout/planout-www2014.pdf)) we log outcomes for each user every day, and then just join the exposure logs onto these tables.  With these joined tables, we can then apply the sorts of standard statistical procedures we illustrate in the notebooks

Since a lot of this depends on exactly how and where you are storying your data, we haven't devoted too much time in our docs or codebase to addressing this problem.  If you are finding that this isn't sufficient and you'd like to work on some more stream-lined, python-based solution I'd be happy to sync up offline on figuring out how we can have some kind of simple extension for doing this.

Cheers,
eytan

**Comment by LABCAO** [comment]
Hi @eytan,

Thank you very much for your comments! The online tutorial gives a big picture of the whole process, and it's greatly appreciated! 

BTW, could you please also advise on how to decrease number of experiments needed to find the best configuration / values of the parameters of an experiment? As there are large numbers of factors and their combinations to evaluate.

Thanks!

**Comment by eytan** [comment]
If you have a factorial design you could use a linear model to borrow strength across conditions that share the same factor levels.  If you believe that you mostly have main effects without interactions you can consider using a fractional factorial design.  Or, with some work you can just use multi-armed bandits to select the best configuration --- it's very straightforward to implement batch-based Thompson sampling with PlanOut, although this would require that you build out automated data analysis and launching infrastructure.

**Comment by LABCAO** [comment]
Hi @eytan,

Thank you so much for your advice! Will give them a try.

Best Wishes,
LABCAO
