### ISSUE TITLE
Versioning and k-v units

### ISSUE THREAD

**Issue by rcs** [facebook/planout#34]
Cheers for opening this up and sharing your work. It’s lovely to see such a succinct implementation of these powerful concepts.

A couple of questions came up while I was looking at implementing a PlanOut variant:

1. How do you handle versioning of the core specification? If you were to add a new operator, is that captured anywhere in the JSON specs that are passed around?

2. Why are units to operators used as a list instead of as a k-v map? Lists seem like they’d be easier to mess up in client implementations by accidentally switching the order. Do you see a downside to extending things to include hashes of strings like `user_signup.my_exp.button_color.{"userid":"42"}`?

Thanks much.

**Comment by eytan** [comment]
Closing this task out because it's not a behavior I would consider changing. Feel free to send me a PR or email me (my github user name at fb dot com) if you have any ideas for a concrete technological solution to the versioning.  Also, FWIW, in the future we are going to have a standardized, cross-platform test suite, which I hope to make more exhaustive.  Hopefully this should provide sufficient coverage for cases where other implementations of PlanOut don't match the reference implementation.
