### ISSUE TITLE
How should namespace segments be used?

### ISSUE THREAD

**Issue by garrettwilkin** [facebook/planout#49]
# Namespaces are awesome but confusing

I realize that using namespaces allows me to run multiple experiments while ensuring that users are assigned to experiments in a mutually exclusive fashion. I love it and need it for that feature. The following behaviors that I observed confused me.

#### Should num_segments represent an estimation of the total population of users?

The primary unit in the experiment is the user ID. We have about 1,000,000 monthly unique visitors to our website where we are running this experiment. So I thought I should set the num_segments to something in the 100,000s so that I'll have sample size large enough to give us high confidence in measuring the impact of the experiment. When I set the num_segments to something in that range, it seems that the Namespace really slows down. Should that be the case? 

#### Is the allocation of the segments to the running experiments simply a method of determining the distribution of users to experiments?  

* For instance, if I had num_segments = 100, and assigned experiment 1 to 40 segments and experiment 2 to 60 segments, would I see roughly a 40% allocation of users to experiment 1?
* With num_segments set to 100, and 20 allocated to experiment 1 and 20 allocated to experiment 2, would I see 60% of users assigned to the default experiment, if I defined one?

**Comment by eytan** [comment]
Hi @garrettwilkin ,

1) Should num_segments represent an estimation of the total population of users?
num_segments only determines the granularity of the size of experiments you want to run.  If you use 10,000 segments (which is what we use at Facebook), then the smallest experiment you can run involves 1/10000 = 0.01% of your users (so in your case, 100 users).  Of course, then the actual randomization to parameters happens via the hashing in the PlanOut script... So 10k segments may even be more granular than what you need.

2) Is the default_experiment only used when the total of segments allocated to experiments is less than num_segments?
default_experiment is also used when users are disqualified from the experiment (see code from [namespace.py](https://github.com/facebook/planout/blob/master/python/planout/namespace.py#L179).  

This will happen if your PlanOut script executes the code "return false;".  The main use cases for return false include gating, e.g.,:

```
if(gating_check(userid=userid, restraint="my_experiment_name")) {
  return false;
}
```

where gating_check() is some custom operator that might hit a service that checks to see if the userid is eligible to be in the experiment, like if you want your experiment to gate on users from a certain country.  

You can also use this "return false;" construct if you are running an experiment and it turns out some parameter causes a bug, so like:

```
x = uniformChoice(choices=[10, 20, 50, 100], unit=userid);
if(choices==100) {
  return false;
}
```
In cases where you were running your experiment and found out that 100 really screwed things up.

3) Is the allocation of the segments to the running experiments simply a method of determining the distribution of users to experiments?

That's correct.  The allocation of segments is a deterministic mapping from input units (like userids) to experiments.  This allocation should be random to some fixed number of segments, and typically these allocations get stored in a database or datastore which contains rows like, (namespace, segmentid, experiment), so that you can hash the userid to a segment id, and then simply pull the experiment that corresponds to the appropriate (namespace, segment_id) key.

**Comment by eytan** [comment]
@garrettwilkin , I am going to close this out.  Feel free to drop me an email if you have any more questions.
