### ISSUE TITLE
Namespace autoExposureLogging is broken

### ISSUE THREAD

**Issue by rawls238** [facebook/planout#69]
We ran into this today in the JS implementation...I looked at the Python implementation and I think it suffers the same issue...

Here are the steps to reproduce:

1) Have auto exposure logging enabled on all the experiments in a namespace
2) Get an experiment parameter for experiment A
3) For a user that is enrolled in experiment B, it simply checks that _experiment is set to something and tries to get the param from _experiment  (in this case, experiment B).
4) When it tries to get the experiment parameter it automatically logs exposure for experiment B, even if the requested parameter is null or doesn't exist and the intention was to get the experiment parameter from experiment A, exposure was logged on experiment B.

Exposure shouldn't be logged in this case on experiment B, but given the existing implementation (at least in the JS + Python implementations) it is logged. Let me know if you agree that this is a bug or if perhaps something is wrong with how we are using namespaces.

@eytan

**Comment by rawls238** [comment]
if this is indeed a bug, I'm not quite sure how to resolve it since it's perfectly valid for an experiment parameter to return null (and still have the user be enrolled in an experiment)

**Comment by eytan** [comment]
Hi @rawls238 -- if a user is assigned to a particular experiment in a namespace, and the requested parameter is not set by the experiment, an error should be logged somewhere, and the default value that is hardcoded in the Python/JS should be used.  No exposure logging should be happening because exposure logs should only happen when units are being randomly assigned to some condition.

**Comment by rawls238** [comment]
@eytan 

I agree that that ought to be the intended behavior. I'm not sure of the best place for the logic that ensures that (i.e. in the experiment or in the namespace).

From my reading of the current code (https://github.com/facebook/planout/blob/master/python/planout/experiment.py#L172), it logs exposure regardless of the return value of the _assignment.get function. That means that if you're invoking the get method on experiment B in the scenario above then the implementation of SimpleNamespace does no sanity checking to see if the value could have ever been assigned to experiment B and logs exposure on experiment B regardless.

We could either add some metadata to the experiment class that describe what the actual parameters that the experiment can set are or we could have the namespaces be in charge of this.

**Comment by eytan** [comment]
@rawls238, I think we should go with both solutions (which is what we do at Facebook): for namespace-based experiments, the parameter validation should occur at the namespace level, but for experiments not running in a namespace, this check should happen at the experiment level.

One thing about this experimentParameters() method that you have is that you can have different implementations, so that down the road you can use metadata, rather than the runtime analysis of the JS code that you are currently doing.

Also, do you have any plans to move to a strongly typed variant of JS like Flow?  We are in the process of improving the way we handle types in the Hack implementation of PlanOut to make it more type safe.  We would do this by implementing a getParamTypes() method that returns the names and types of all parameters that are defined.  When the user calls a typed getter (e.g., getInt(), getString()), we check if the parameter is defined, and furthermore that the requested type corresponds to the known type of the data.  Additional type checking occurs via static analysis of the PlanOut scripts.  These kinds of checks could even be useful in Python or JS when metadata is available, as a way of detecting/preventing bugs, even though the type information isn't actually required by the language.

**Comment by rawls238** [comment]
We can probably close this as I think we've discussed this issue in depth at this point and this, https://github.com/facebook/planout/pull/76, should provide the necessary remedy to this issue (as well as the discussion in this thread partially since this touches upon where I think the issue truly originates from: https://github.com/HubSpot/react-experiments/issues/11).
