### ISSUE TITLE
PlanOut Compiler Demo broken on Firefox 41.0.2

### ISSUE THREAD

**Issue by tsujeeth** [facebook/planout#86]
![screen shot 2015-10-23 at 12 40 13 pm](https://cloud.githubusercontent.com/assets/441585/10703335/327d7578-7984-11e5-8dc7-e16720e5a7d2.png)

OS: Mac, Yosemite 10.10.4

It works correctly on Safari.

https://facebook.github.io/planout/demo/planout-compiler.html

**Comment by eytan** [comment]
@tsujeeth I don't think I am going to bother with fixing this since there is a more full featured PlanOut editor that knocks this demo out of the water.  It's available both on github and live at http://planout-editor.herokuapp.com/ ... Let me know if you are experiencing any compatibility issues with that.

**Comment by tsujeeth** [comment]
That works. Thanks!
